---
name: ((deployment_name))

releases:
  - name: caddy
    version: latest
  - name: bpm
    version: latest

stemcells:
  - alias: default
    os: ubuntu-jammy
    version: latest

instance_groups:
  - name: caddy
    azs: [z1]
    instances: 1
    vm_type: ((vm_type))
    stemcell: default
    persistent_disk: ((persistent_disk))
    networks:
      - name: ((network_name))
    jobs:
      - name: bpm
        release: bpm
      - name: caddy
        release: caddy
        properties:
          env:
            GCP_PROJECT: ((gcp_project))
            GOOGLE_APPLICATION_CREDENTIALS: ((google_application_credentials))
          caddyfile: ((caddyfile))

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000-300000
  update_watch_time: 30000-300000
